""" Josh Bacon
 face1.py
 Program draws spongebob's face
"""
import turtle
import math
import random

#Draws eyes using circles and lines
def drawEyes(pen) :
    pen.setheading(180)
    pen.up()
    pen.goto(39, 64)
    pen.down()
    pen.goto(40, 69)
    pen.up()
    pen.goto(35, 64)
    pen.down()
    pen.goto(34, 69)
    pen.up()
    pen.goto(30, 62)
    pen.down()
    pen.goto(29, 67)
    pen.up()
    pen.fillcolor("white")
    pen.begin_fill()
    drawCircle(pen, 37, 65, 10)
    pen.end_fill()
    pen.fillcolor("blue")
    pen.begin_fill()
    drawCircle(pen, 40, 60, 4)
    pen.end_fill()
    pen.fillcolor("black")
    pen.begin_fill()
    drawCircle(pen, 41, 59, 3)
    pen.end_fill()
    pen.up()
    pen.goto(61, 64)
    pen.down()
    pen.goto(60, 69)
    pen.up()
    pen.goto(65, 64)
    pen.down()
    pen.goto(64, 69)
    pen.up()
    pen.goto(70, 62)
    pen.down()
    pen.goto(71, 67)
    pen.up()
    pen.fillcolor("white")
    pen.begin_fill()
    drawCircle(pen, 63, 65, 10)
    pen.end_fill()
    pen.fillcolor("blue")
    pen.begin_fill()
    drawCircle(pen, 60, 60, 4)
    pen.end_fill()
    pen.fillcolor("black")
    pen.begin_fill()
    drawCircle(pen, 59, 59, 3)
    pen.end_fill()

#Draws nose with arcs and lines
def drawNose(pen) :
    pen.setheading(90)
    pen.up()
    pen.goto(47,40)
    pen.down()
    pen.goto(46,50)
    drawArc(pen, 46, 50, -4, 180)
    pen.up()
    pen.goto(54,50)
    pen.down()
    pen.goto(53,40)
    pen.up()

#Draws ears (orange circles) with circles
def drawEars(pen) :
    pen.up()
    pen.fillcolor("orange")
    pen.begin_fill()
    drawCircle(pen, 60, 85, 5)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 55, 10, 5)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 80, 50, 5)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 10, 10, 7)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 80, 15, 7)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 80, 80, 7)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 20, 80, 7)
    pen.end_fill()
    pen.begin_fill()
    drawCircle(pen, 8, 48, 5)
    pen.end_fill()
    
#Draws one hair with arcs and lines
def drawHair(pen) :
    pen.up()
    pen.goto(50, 85)
    pen.down()
    pen.goto(50, 92)
    pen.goto(51, 93)
    pen.goto(52, 94)
    pen.goto(52, 96)
    pen.goto(51, 97)
    pen.goto(50, 98)
    pen.goto(49, 98)
    pen.up()
    

#Draws mouth with rectangles, arcs, and lines
def drawMouth(pen) :
    
    #Draws Mouth using arcs
    pen.setheading(90)
    pen.fillcolor("red")
    pen.begin_fill()
    pen.up()
    pen.goto(70,40)
    pen.down()
    pen.goto(60,35)
    pen.goto(50,34)
    pen.goto(40, 35)
    pen.goto(30,40)
    drawArc(pen, 30, 40, -20, -180)
    pen.end_fill()
    #Draws Teeth rectangles
    pen.fillcolor("white")
    pen.begin_fill()
    drawRectangle(pen, 43, 35, 48, 30)
    pen.end_fill()
    pen.begin_fill()
    drawRectangle(pen, 52, 30, 57, 35)
    pen.end_fill()
    """
    pen.up()
    pen.begin_fill()
    pen.goto(43, 35)
    pen.goto(48, 34)
    pen.goto(48, 30)
    pen.goto(43, 30)
    pen.goto(43, 35)
    pen.end_fill()
    pen.up()
    pen.begin_fill()
    pen.goto(57, 35)
    pen.goto(52, 34)
    pen.goto(52, 30)
    pen.goto(57, 30)
    pen.goto(57, 35)
    pen.end_fill()
    """
    #Draws Tongue
    pen.fillcolor("pink")
    pen.begin_fill()
    pen.goto(43, 21)
    pen.goto(48, 24)
    pen.goto(52, 24)
    pen.goto(57, 21)
    pen.goto(50, 20)
    pen.goto(43, 21)
    pen.end_fill()
    #Draws Cheeks
    pen.up()
    pen.setheading(90)
    drawArc(pen, 33, 42, 3, 225)
    pen.setheading(90)
    drawArc(pen, 67, 42, -3, 225)

#Draws a circle with radius
def drawCircle(pen, xCenter, yCenter, radius) :
    pen.up()
    pen.goto(xCenter, yCenter)
    pen.down()
    pen.circle(radius)

#Draws an arc with extent and radius
def drawArc(pen, xCenter, yCenter, radius, extent) :
    pen.up()
    pen.goto(xCenter, yCenter)
    pen.down()
    pen.circle(radius, extent)
    pen.up()

def drawRectangle(pen, xBotLeftCorner, yBotLeftCorner, xTopRightCorner, yTopRightCorner) :
    width = xTopRightCorner - xBotLeftCorner
    height = yTopRightCorner - yBotLeftCorner
    pen.setheading(90)
    pen.goto(xBotLeftCorner, yBotLeftCorner)
    pen.forward(height)
    pen.right(90)
    pen.forward(width)
    pen.right(90)
    pen.forward(height)
    pen.right(90)
    pen.forward(width)
    pen.right(90)

def main() :
    screen = turtle.Screen()
    screen.setworldcoordinates(0,0,100,100)
    screen.tracer(1000)
    turtle.bgcolor("yellow")
    pen = turtle.Turtle()
    pen.hideturtle()
    pen.up()
    drawNose(pen)
    drawEyes(pen)
    drawMouth(pen)
    drawEars(pen)
    drawHair(pen)
    screen.exitonclick()
main()
